# Generated by Django 2.0.3 on 2018-05-12 02:47

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import read_statistics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_register', '0009_remove_person_emailname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField(blank=True, default=0)),
                ('pic', models.ImageField(blank=True, upload_to='img', verbose_name='上传图片')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login_register.Person')),
            ],
            options={
                'ordering': ['-created_time'],
            },
            bases=(models.Model, read_statistics.models.ReadNumExpandMethod),
        ),
        migrations.CreateModel(
            name='ItemState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(default='', max_length=30, verbose_name='状态')),
                ('permission', models.IntegerField(default=3, verbose_name='状态等级')),
            ],
            bases=(models.Model, read_statistics.models.ReadNumExpandMethod),
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
            bases=(models.Model, read_statistics.models.ReadNumExpandMethod),
        ),
        migrations.AddField(
            model_name='item',
            name='item_state',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='item.ItemState'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='item.ItemType'),
        ),
    ]
