# Generated by Django 2.0.2 on 2018-04-11 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_time']},
        ),
    ]
