# Generated by Django 2.0.4 on 2018-04-13 11:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20180411_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
