# Generated by Django 2.0.2 on 2018-04-05 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0003_auto_20180405_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='grade',
            field=models.ForeignKey(default='大学一年级', on_delete=django.db.models.deletion.CASCADE, to='login_register.User_Grade'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.ForeignKey(default='访客', on_delete=django.db.models.deletion.CASCADE, to='login_register.User_Role'),
        ),
    ]
