# Generated by Django 2.0.2 on 2018-04-05 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0004_auto_20180405_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='grade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login_register.User_Grade'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='login_register.User_Role'),
        ),
        migrations.AlterField(
            model_name='user_grade',
            name='gradename',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='user_role',
            name='rolename',
            field=models.CharField(default='', max_length=30, verbose_name='名称'),
        ),
    ]
