# Generated by Django 2.0.2 on 2018-04-05 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0005_auto_20180405_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=0, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='person',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_register.User_Grade'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login_register.User_Role'),
        ),
        migrations.AlterField(
            model_name='person',
            name='telephone',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='联系电话'),
        ),
    ]
