# Generated by Django 2.0.2 on 2018-04-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0007_auto_20180409_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(default='', max_length=50, verbose_name='邮箱地址'),
        ),
        migrations.AddField(
            model_name='person',
            name='emailname',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
