# Generated by Django 2.0.2 on 2018-04-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0008_auto_20180418_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='emailname',
        ),
    ]
